use std::{collections::HashSet, fs, io, path::PathBuf};

struct Problem {
    number: u32,
    slug: String,
    title: String,
    category: String,
    level: String,
    percent: String,
    description: String,
    source: String,
}

fn parse_range() -> Option<(Option<u32>, Option<u32>)> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.len() {
        0 => None,
        1 => args[0].parse::<u32>().ok().map(|to| (None, Some(to))),
        _ => {
            let from = args[0].parse::<u32>().ok()?;
            let to = args[1].parse::<u32>().ok()?;
            Some((Some(from), Some(to)))
        }
    }
}

fn main() -> io::Result<()> {
    let home = std::env::var("HOME").expect("HOME not set");
    let root = PathBuf::from(home).join("leetcode-rs");
    let solutions_dir = root.join("solutions");
    let range = parse_range();

    let mut problems = Vec::new();

    for entry in fs::read_dir(&solutions_dir)? {
        let path = entry?.path();
        if !path.is_file() {
            continue;
        }

        let file = match path.file_name().and_then(|s| s.to_str()) {
            Some(f) => f,
            None => continue,
        };

        if let Some((num, rest)) = file.split_once('.') {
            if !num.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }
            if rest.ends_with(".rs") {
                let p = parse_problem(&path)?;
                if let Some((from, to)) = range {
                    if let Some(f) = from {
                        if p.number < f {
                            continue;
                        }
                    }
                    if let Some(t) = to {
                        if p.number > t {
                            continue;
                        }
                    }
                }
                problems.push(p);
            }
        }
    }

    problems.sort_by_key(|p| p.number);

    generate_analysis_lib(&root, &problems)?;
    generate_problem_readmes(&problems, &root)?;
    cleanup_orphan_readmes(&problems, &root)?;
    generate_index_readme(&problems, &root)?;

    Ok(())
}

fn parse_problem(path: &PathBuf) -> io::Result<Problem> {
    let content = fs::read_to_string(path)?;

    let mut category = String::new();
    let mut level = String::new();
    let mut percent = String::new();
    let mut desc = Vec::new();

    for line in content.lines() {
        let l = line.trim();
        if l.starts_with("// Category:") {
            category = l[12..].trim().to_string();
        } else if l.starts_with("// Level:") {
            level = l[9..].trim().to_string();
        } else if l.starts_with("// Percent:") {
            percent = l[11..].trim().to_string();
        } else if l.starts_with("//") {
            desc.push(l.trim_start_matches("//").trim().to_string());
        } else if l.starts_with("use ") || l.starts_with("impl ") {
            break;
        }
    }

    let file = path.file_name().unwrap().to_str().unwrap();
    let (num, slug) = file.split_once('.').unwrap();
    let slug = slug.strip_suffix(".rs").unwrap();

    Ok(Problem {
        number: num.parse().unwrap(),
        slug: slug.to_string(),
        title: title_case(slug),
        category,
        level,
        percent,
        description: desc.join("\n"),
        source: format!("solutions/{}.{}.rs", num, slug),
    })
}

fn generate_analysis_lib(root: &PathBuf, problems: &[Problem]) -> io::Result<()> {
    let src = root.join("src");
    fs::create_dir_all(&src)?;
    let mut out = String::new();

    out.push_str(
"//! Analysis-only crate root.\n\
//!\n\
//! This file is auto-generated by `sync_leetcode`.\n\
//! It exists solely to enable IDE tooling (rust-analyzer, auto-complete,\n\
//! go-to-definition, diagnostics).\n\
//!\n\
//! Solutions live under `solutions/` and are NOT intended to be compiled\n\
//! as part of this crate.\n\n");

    out.push_str("#![allow(dead_code)]\n#![allow(unused_imports)]\n#![allow(unused_variables)]\n#![allow(non_snake_case)]\n\nmod solutions {\n");
    for p in problems {
        out.push_str(&format!("    include!(\"../{}\");\n", p.source));
    }
    out.push_str("}\n");
    fs::write(src.join("lib.rs"), out)
}

fn generate_problem_readmes(problems: &[Problem], root: &PathBuf) -> io::Result<()> {
    let dir = root.join("problems");
    fs::create_dir_all(&dir)?;

    for p in problems {
        let path = dir.join(format!("{:03}-{}.md", p.number, p.slug));
        let mut out = String::new();

        out.push_str(&format!(
            "# {}. {}\n\n**Category:** {}  \n**Difficulty:** {}  \n**Acceptance Rate:** {}\n\n",
            p.number, p.title, p.category, p.level, p.percent
        ));

        out.push_str(&format!(
            "**LeetCode:** [Open problem on leetcode.com](https://leetcode.com/problems/{}/)\n\n---\n\n",
            p.slug
        ));

        out.push_str("## Problem\n\n");

        let mut in_examples = false;
        let mut in_constraints = false;
        let mut example = 0;
        let mut constraints = Vec::new();

        for raw in p.description.lines() {
            let line = raw.trim();

            if line.starts_with("Example") {
                in_examples = true;
                in_constraints = false;
                example += 1;
                out.push_str(&format!("### Example {}\n", example));
                continue;
            }

            if line.starts_with("Constraints") {
                in_constraints = true;
                in_examples = false;
                out.push_str("\n## Constraints\n");
                continue;
            }

            if in_examples {
                if line.starts_with("Input:")
                    || line.starts_with("Output:")
                    || line.starts_with("Explanation:")
                {
                    out.push_str(line);
                    out.push_str("  \n");
                }
                continue;
            }

            if in_constraints {
                if !line.is_empty() {
                    constraints.push(line.to_string());
                }
                continue;
            }

            if !line.is_empty() {
                out.push_str(line);
                out.push_str("\n\n");
            }
        }

        if !constraints.is_empty() {
            out.push('\n');
            for (i, c) in constraints.iter().enumerate() {
                out.push_str(c);
                if i + 1 < constraints.len() {
                    out.push_str("  \n");
                }
            }
            out.push('\n');
        }

        let test_path = format!("solutions/{}.{}.tests.dat", p.number, p.slug);
        if root.join(&test_path).exists() {
            out.push_str("\n---\n\n## Test Data\n\n");
            out.push_str(&format!("- [{}](../{})\n", test_path, test_path));
        }

        out.push_str("\n---\n\n## Source / Solution\n\n");
        out.push_str(&format!("- [{}](../{})\n", p.source, p.source));

        fs::write(path, out)?;
    }

    Ok(())
}

fn cleanup_orphan_readmes(problems: &[Problem], root: &PathBuf) -> io::Result<()> {
    let dir = root.join("problems");
    if !dir.exists() {
        return Ok(());
    }

    let expected: HashSet<String> = problems
        .iter()
        .map(|p| format!("{:03}-{}.md", p.number, p.slug))
        .collect();

    for entry in fs::read_dir(&dir)? {
        let path = entry?.path();
        if let Some(name) = path.file_name().and_then(|s| s.to_str()) {
            if !expected.contains(name) {
                fs::remove_file(path)?;
            }
        }
    }

    Ok(())
}

fn generate_index_readme(problems: &[Problem], root: &PathBuf) -> io::Result<()> {
    let mut out = String::new();

    out.push_str("# LeetCode Solutions (Rust)\n\n");
    out.push_str("> This repository is documentation-focused.\n");
    out.push_str("> Individual problems are documented under the `problems/` directory.\n\n");
    out.push_str("![Rust](https://img.shields.io/badge/language-Rust-orange)\n\n");

    out.push_str("| # | Problem | Difficulty | Category |\n");
    out.push_str("|---|--------|------------|----------|\n");

    for p in problems {
        out.push_str(&format!(
            "| {} | [{}](problems/{:03}-{}.md) | {} | {} |\n",
            p.number, p.title, p.number, p.slug, p.level, p.category
        ));
    }

    out.push_str("\n---\n\n## Scope\n\n");
    out.push_str("- Documentation-focused\n");
    out.push_str("- No execution or benchmarking\n");
    out.push_str("- Auto-generated documentation\n");

    out.push_str("\n---\n\n## Notes\n\n");
    out.push_str("- `solutions/` is the source of truth\n");
    out.push_str("- Generated files should not be edited manually\n");

    out.push_str("\n---\n\n## Credits\n\n");
    out.push_str("- https://github.com/clearloop/leetcode-cli\n");

    fs::write(root.join("README.md"), out)
}

fn title_case(slug: &str) -> String {
    slug.split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
