use std::{
    collections::{BTreeMap, HashSet},
    fs,
    io,
    path::PathBuf,
};

struct Problem {
    number: u32,
    slug: String,
    title: String,
    category: String,
    level: String,
    percent: String,
    description: String,
    source: String,
}

fn parse_range() -> Option<(Option<u32>, Option<u32>)> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.len() {
        0 => None,
        1 => args[0].parse::<u32>().ok().map(|to| (None, Some(to))),
        _ => {
            let a = args[0].parse::<u32>().ok()?;
            let b = args[1].parse::<u32>().ok()?;
            let (from, to) = if a <= b { (a, b) } else { (b, a) };
            Some((Some(from), Some(to)))
        }
    }
}

fn bucket_size(total: usize) -> u32 {
    match total {
        0..=50 => 10,
        51..=200 => 25,
        201..=500 => 50,
        _ => 100,
    }
}

fn main() -> io::Result<()> {
    let home = std::env::var("HOME").expect("HOME not set");
    let root = PathBuf::from(home).join("leetcode-rs");
    let solutions_dir = root.join("solutions");
    let range = parse_range();

    let mut problems = Vec::new();

    for entry in fs::read_dir(&solutions_dir)? {
        let path = entry?.path();
        if !path.is_file() {
            continue;
        }

        let file = match path.file_name().and_then(|s| s.to_str()) {
            Some(f) => f,
            None => continue,
        };

        if let Some((num, rest)) = file.split_once('.') {
            if !num.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }
            if rest.ends_with(".rs") {
                let p = parse_problem(&path)?;
                if let Some((from, to)) = range {
                    if let Some(f) = from {
                        if p.number < f {
                            continue;
                        }
                    }
                    if let Some(t) = to {
                        if p.number > t {
                            continue;
                        }
                    }
                }
                problems.push(p);
            }
        }
    }

    problems.sort_by_key(|p| p.number);

    generate_analysis_lib(&root, &problems)?;
    generate_problem_readmes(&problems, &root)?;
    cleanup_orphan_readmes(&problems, &root)?;
    generate_index_readme(&problems, &root)?;

    Ok(())
}

fn parse_problem(path: &PathBuf) -> io::Result<Problem> {
    let content = fs::read_to_string(path)?;

    let mut category = String::new();
    let mut level = String::new();
    let mut percent = String::new();
    let mut desc = Vec::new();

    for line in content.lines() {
        let l = line.trim();
        if l.starts_with("// Category:") {
            category = l[12..].trim().to_string();
        } else if l.starts_with("// Level:") {
            level = l[9..].trim().to_string();
        } else if l.starts_with("// Percent:") {
            percent = l[11..].trim().to_string();
        } else if l.starts_with("//") {
            desc.push(l.trim_start_matches("//").trim().to_string());
        } else if l.starts_with("use ") || l.starts_with("impl ") {
            break;
        }
    }

    let file = path.file_name().unwrap().to_str().unwrap();
    let (num, slug) = file.split_once('.').unwrap();
    let slug = slug.strip_suffix(".rs").unwrap();

    Ok(Problem {
        number: num.parse().unwrap(),
        slug: slug.to_string(),
        title: title_case(slug),
        category,
        level,
        percent,
        description: desc.join("\n"),
        source: format!("solutions/{}.{}.rs", num, slug),
    })
}

fn generate_analysis_lib(root: &PathBuf, problems: &[Problem]) -> io::Result<()> {
    let src = root.join("src");
    fs::create_dir_all(&src)?;

    let mut out = String::new();
    out.push_str(
"//! Analysis-only crate root.
//!
//! Auto-generated by sync_leetcode.
//! Enables rust-analyzer and IDE tooling only.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

mod solutions {
");

    for p in problems {
        out.push_str(&format!("    include!(\"../{}\");\n", p.source));
    }

    out.push_str("}\n");
    fs::write(src.join("lib.rs"), out)
}

fn generate_problem_readmes(problems: &[Problem], root: &PathBuf) -> io::Result<()> {
    let dir = root.join("problems");
    fs::create_dir_all(&dir)?;

    for p in problems {
        let path = dir.join(format!("{:03}-{}.md", p.number, p.slug));
        let mut out = String::new();

        out.push_str(&format!(
            "# {}. {}\n\n",
            p.number, p.title
        ));

        out.push_str(&format!(
            "**Category:** {}\n\
**Difficulty:** {}\n\
**Acceptance:** {}\n\n",
            p.category, p.level, p.percent
        ));

        out.push_str(&format!(
            "**LeetCode:** https://leetcode.com/problems/{}/\n\n",
            p.slug
        ));

        let mut in_examples = false;
        let mut in_constraints = false;
        let mut example_idx = 0;

        out.push_str("---\n\n## Problem\n\n");

        for raw in p.description.lines() {
            let line = raw.trim();

            if line.is_empty() {
                continue;
            }

            if line.starts_with("Example") {
                if !in_examples {
                    out.push_str("\n---\n\n## Examples\n\n");
                    in_examples = true;
                }
                example_idx += 1;
                out.push_str(&format!("### Example {}\n", example_idx));
                continue;
            }

            if line.starts_with("Constraints") {
                out.push_str("\n---\n\n## Constraints\n\n");
                in_examples = false;
                in_constraints = true;
                continue;
            }

            if in_examples {
                if line.starts_with("Input:")
                    || line.starts_with("Output:")
                    || line.starts_with("Explanation:")
                {
                    out.push_str(line);
                    out.push('\n');
                }
                continue;
            }

            if in_constraints {
                out.push_str(line);
                out.push('\n');
                continue;
            }

            out.push_str(line);
            out.push_str("\n\n");
        }

        let test_path = format!("solutions/{}.{}.tests.dat", p.number, p.slug);
        if root.join(&test_path).exists() {
            out.push_str("\n---\n\n## Test Data\n\n");
            out.push_str(&format!("{}\n", test_path));
        }

        out.push_str("\n---\n\n## Source / Solution\n\n");
        out.push_str(&format!("{}\n", p.source));

        fs::write(path, out)?;
    }

    Ok(())
}

fn cleanup_orphan_readmes(problems: &[Problem], root: &PathBuf) -> io::Result<()> {
    let dir = root.join("problems");
    if !dir.exists() {
        return Ok(());
    }

    let expected: HashSet<String> = problems
        .iter()
        .map(|p| format!("{:03}-{}.md", p.number, p.slug))
        .collect();

    for entry in fs::read_dir(&dir)? {
        let path = entry?.path();
        if let Some(name) = path.file_name().and_then(|s| s.to_str()) {
            if !expected.contains(name) {
                fs::remove_file(path)?;
            }
        }
    }

    Ok(())
}

fn generate_index_readme(problems: &[Problem], root: &PathBuf) -> io::Result<()> {
    let bucket = bucket_size(problems.len());

    let total = problems.len();
    let mut easy = 0;
    let mut medium = 0;
    let mut hard = 0;

    for p in problems {
        match p.level.as_str() {
            "Easy" => easy += 1,
            "Medium" => medium += 1,
            "Hard" => hard += 1,
            _ => {}
        }
    }

    let mut buckets: BTreeMap<u32, Vec<&Problem>> = BTreeMap::new();
    for p in problems {
        let start = ((p.number - 1) / bucket) * bucket + 1;
        buckets.entry(start).or_default().push(p);
    }

    let mut out = String::new();

    out.push_str("# LeetCode Solutions (Rust)\n\n");
    out.push_str(
        "This repository contains a curated collection of LeetCode solutions written in Rust,\n\
with a focus on clarity, correctness, and maintainable documentation.\n\n\
The repository is updated daily as part of a personal challenge to solve one\n\
LeetCode problem per day.\n\n",
    );

    out.push_str("## Statistics\n\n");
    out.push_str(&format!(
        "- **Total problems:** {}\n- **Difficulty breakdown:**\n  - Easy: {}\n  - Medium: {}\n  - Hard: {}\n\n",
        total, easy, medium, hard
    ));

    out.push_str(
        "> This is a documentation-focused repository.  \n\
> Individual problems are documented in detail under the `problems/` directory.\n\n",
    );

    out.push_str("![Rust](https://img.shields.io/badge/language-Rust-orange)\n\n");

    out.push_str("## Quick Navigation\n\n");

    for (start, group) in &buckets {
        if !group.is_empty() {
            let end = start + bucket - 1;
            out.push_str(&format!(
                "- [Problems {}–{}](#problems-{}–{})\n",
                start, end, start, end
            ));
        }
    }

    for (start, group) in &buckets {
        let end = start + bucket - 1;
        out.push_str(&format!("\n---\n\n## Problems {}–{}\n\n", start, end));
        out.push_str("| # | Problem | Difficulty | Category |\n");
        out.push_str("|---|--------|------------|----------|\n");

        let mut g = group.clone();
        g.sort_by_key(|p| p.number);

        for p in g {
            out.push_str(&format!(
                "| {} | [{}](problems/{:03}-{}.md) | {} | {} |\n",
                p.number, p.title, p.number, p.slug, p.level, p.category
            ));
        }

        out.push_str("\n[Back to top](#leetcode-solutions-rust)\n");
    }

    out.push_str("\n---\n\n## Repository Structure\n\n");
    out.push_str(
        "```text\n\
leetcode-rs/\n\
├── solutions/        # Original Rust solution files (source of truth)\n\
├── problems/         # Auto-generated per-problem documentation\n\
├── src/              # Analysis-only crate root (rust-analyzer)\n\
├── tools/            # Synchronization tooling\n\
├── Cargo.toml        # Minimal Cargo manifest\n\
└── README.md         # Repository overview\n\
```\n",
    );

    out.push_str("\n---\n\n## Tooling and Synchronization\n\n");
    out.push_str(
        "A custom synchronization tool (`sync_leetcode`) is used to keep solution\n\
files, documentation, and metadata in sync.\n\n\
```bash\n\
cd ~/leetcode-rs\n\
rustc tools/sync_leetcode.rs -O -o tools/sync_leetcode\n\
./tools/sync_leetcode\n\
./tools/sync_leetcode 100\n\
```\n",
    );

    out.push_str("\n---\n\n## Scope and Design Goals\n\n");
    out.push_str(
        "- Readable and idiomatic Rust solutions\n\
- No execution or benchmarking\n\
- Deterministic, auto-generated documentation\n\
- Strong IDE support via rust-analyzer\n",
    );

    out.push_str("\n---\n\n## Notes\n\n");
    out.push_str(
        "- `solutions/` is the single source of truth\n\
- Files under `problems/` and `src/` are auto-generated\n\
- Manual edits to generated files will be overwritten\n",
    );

    out.push_str("\n---\n\n## Credits\n\n");
    out.push_str("- https://github.com/clearloop/leetcode-cli\n");

    fs::write(root.join("README.md"), out)
}

fn title_case(slug: &str) -> String {
    slug.split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
