//! Analysis-only crate root.
//!
//! This file is auto-generated by `sync_leetcode`.
//! It exists solely to enable IDE tooling (rust-analyzer, auto-complete,
//! go-to-definition, diagnostics).
//!
//! Solutions live under `solutions/` and are NOT intended to be compiled
//! as part of this crate.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

mod solutions {
    include!("../solutions/1.two-sum.rs");
    include!("../solutions/2.add-two-numbers.rs");
    include!("../solutions/3.longest-substring-without-repeating-characters.rs");
    include!("../solutions/4.median-of-two-sorted-arrays.rs");
}
