//! Analysis-only crate root.
//!
//! Auto-generated by sync_leetcode.
//! Enables rust-analyzer and IDE tooling only.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

mod solutions {
}
