//! Analysis-only crate root.
//!
//! Auto-generated by sync_leetcode.
//! Enables rust-analyzer and IDE tooling only.

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

mod solutions {
    include!("../solutions/1.two-sum.rs");
    include!("../solutions/2.add-two-numbers.rs");
    include!("../solutions/3.longest-substring-without-repeating-characters.rs");
    include!("../solutions/4.median-of-two-sorted-arrays.rs");
    include!("../solutions/5.longest-palindromic-substring.rs");
}
